// see https://datoviz.org/reference/colormaps/ prefer cyclical ones 92-97
// https://github.com/datoviz/data/blob/main/textures/cmap_atlas.csv
// for https://github.com/datoviz/data/blob/main/textures/cmap_atlas.png

export default {
    columns: [
        "name",
        "row",
        "col",
        "size"
    ],
    rows: [
        [
            "BINARY",
            0,
            0,
            256
        ],
        [
            "HSV",
            1,
            0,
            256
        ],
        [
            "CIVIDIS",
            2,
            0,
            256
        ],
        [
            "HSV",
            3,
            0,
            256
        ],
        [
            "MAGMA",
            4,
            0,
            256
        ],
        [
            "PLASMA",
            5,
            0,
            256
        ],
        [
            "VIRIDIS",
            6,
            0,
            256
        ],
        [
            "BLUES",
            7,
            0,
            256
        ],
        [
            "BUGN",
            8,
            0,
            256
        ],
        [
            "BUPU",
            9,
            0,
            256
        ],
        [
            "GNBU",
            10,
            0,
            256
        ],
        [
            "GREENS",
            11,
            0,
            256
        ],
        [
            "GREYS",
            12,
            0,
            256
        ],
        [
            "ORANGES",
            13,
            0,
            256
        ],
        [
            "ORRD",
            14,
            0,
            256
        ],
        [
            "PUBU",
            15,
            0,
            256
        ],
        [
            "PUBUGN",
            16,
            0,
            256
        ],
        [
            "PURPLES",
            17,
            0,
            256
        ],
        [
            "RDPU",
            18,
            0,
            256
        ],
        [
            "REDS",
            19,
            0,
            256
        ],
        [
            "YLGN",
            20,
            0,
            256
        ],
        [
            "YLGNBU",
            21,
            0,
            256
        ],
        [
            "YLORBR",
            22,
            0,
            256
        ],
        [
            "YLORRD",
            23,
            0,
            256
        ],
        [
            "AFMHOT",
            24,
            0,
            256
        ],
        [
            "AUTUMN",
            25,
            0,
            256
        ],
        [
            "BONE",
            26,
            0,
            256
        ],
        [
            "COOL",
            27,
            0,
            256
        ],
        [
            "COPPER",
            28,
            0,
            256
        ],
        [
            "GIST_HEAT",
            29,
            0,
            256
        ],
        [
            "GRAY",
            30,
            0,
            256
        ],
        [
            "HOT",
            31,
            0,
            256
        ],
        [
            "PINK",
            32,
            0,
            256
        ],
        [
            "SPRING",
            33,
            0,
            256
        ],
        [
            "SUMMER",
            34,
            0,
            256
        ],
        [
            "WINTER",
            35,
            0,
            256
        ],
        [
            "WISTIA",
            36,
            0,
            256
        ],
        [
            "BRBG",
            37,
            0,
            256
        ],
        [
            "BWR",
            38,
            0,
            256
        ],
        [
            "COOLWARM",
            39,
            0,
            256
        ],
        [
            "PIYG",
            40,
            0,
            256
        ],
        [
            "PRGN",
            41,
            0,
            256
        ],
        [
            "PUOR",
            42,
            0,
            256
        ],
        [
            "RDBU",
            43,
            0,
            256
        ],
        [
            "RDGY",
            44,
            0,
            256
        ],
        [
            "RDYLBU",
            45,
            0,
            256
        ],
        [
            "RDYLGN",
            46,
            0,
            256
        ],
        [
            "SEISMIC",
            47,
            0,
            256
        ],
        [
            "SPECTRAL",
            48,
            0,
            256
        ],
        [
            "TWILIGHT_SHIFTED",
            49,
            0,
            256
        ],
        [
            "TWILIGHT",
            50,
            0,
            256
        ],
        [
            "BRG",
            51,
            0,
            256
        ],
        [
            "CMRMAP",
            52,
            0,
            256
        ],
        [
            "CUBEHELIX",
            53,
            0,
            256
        ],
        [
            "FLAG",
            54,
            0,
            256
        ],
        [
            "GIST_EARTH",
            55,
            0,
            256
        ],
        [
            "GIST_NCAR",
            56,
            0,
            256
        ],
        [
            "GIST_RAINBOW",
            57,
            0,
            256
        ],
        [
            "GIST_STERN",
            58,
            0,
            256
        ],
        [
            "GNUPLOT2",
            59,
            0,
            256
        ],
        [
            "GNUPLOT",
            60,
            0,
            256
        ],
        [
            "JET",
            61,
            0,
            256
        ],
        [
            "NIPY_SPECTRAL",
            62,
            0,
            256
        ],
        [
            "OCEAN",
            63,
            0,
            256
        ],
        [
            "PRISM",
            64,
            0,
            256
        ],
        [
            "RAINBOW",
            65,
            0,
            256
        ],
        [
            "TERRAIN",
            66,
            0,
            256
        ],
        [
            "BKR",
            67,
            0,
            256
        ],
        [
            "BKY",
            68,
            0,
            256
        ],
        [
            "CET_D10",
            69,
            0,
            256
        ],
        [
            "CET_D11",
            70,
            0,
            256
        ],
        [
            "CET_D8",
            71,
            0,
            256
        ],
        [
            "CET_D13",
            72,
            0,
            256
        ],
        [
            "CET_D3",
            73,
            0,
            256
        ],
        [
            "CET_D1A",
            74,
            0,
            256
        ],
        [
            "BJY",
            75,
            0,
            256
        ],
        [
            "GWV",
            76,
            0,
            256
        ],
        [
            "BWY",
            77,
            0,
            256
        ],
        [
            "CET_D12",
            78,
            0,
            256
        ],
        [
            "CET_R3",
            79,
            0,
            256
        ],
        [
            "CET_D9",
            80,
            0,
            256
        ],
        [
            "CWR",
            81,
            0,
            256
        ],
        [
            "CET_CBC1",
            82,
            0,
            256
        ],
        [
            "CET_CBC2",
            83,
            0,
            256
        ],
        [
            "CET_CBL1",
            84,
            0,
            256
        ],
        [
            "CET_CBL2",
            85,
            0,
            256
        ],
        [
            "CET_CBTC1",
            86,
            0,
            256
        ],
        [
            "CET_CBTC2",
            87,
            0,
            256
        ],
        [
            "CET_CBTL1",
            88,
            0,
            256
        ],
        [
            "BGY",
            89,
            0,
            256
        ],
        [
            "BGYW",
            90,
            0,
            256
        ],
        [
            "BMW",
            91,
            0,
            256
        ],
        [
            "CET_C1",
            92,
            0,
            256
        ],
        [
            "CET_C1S",
            93,
            0,
            256
        ],
        [
            "CET_C2",
            94,
            0,
            256
        ],
        [
            "CET_C4",
            95,
            0,
            256
        ],
        [
            "CET_C4S",
            96,
            0,
            256
        ],
        [
            "CET_C5",
            97,
            0,
            256
        ],
        [
            "CET_I1",
            98,
            0,
            256
        ],
        [
            "CET_I3",
            99,
            0,
            256
        ],
        [
            "CET_L10",
            100,
            0,
            256
        ],
        [
            "CET_L11",
            101,
            0,
            256
        ],
        [
            "CET_L12",
            102,
            0,
            256
        ],
        [
            "CET_L16",
            103,
            0,
            256
        ],
        [
            "CET_L17",
            104,
            0,
            256
        ],
        [
            "CET_L18",
            105,
            0,
            256
        ],
        [
            "CET_L19",
            106,
            0,
            256
        ],
        [
            "CET_L4",
            107,
            0,
            256
        ],
        [
            "CET_L7",
            108,
            0,
            256
        ],
        [
            "CET_L8",
            109,
            0,
            256
        ],
        [
            "CET_L9",
            110,
            0,
            256
        ],
        [
            "CET_R1",
            111,
            0,
            256
        ],
        [
            "CET_R2",
            112,
            0,
            256
        ],
        [
            "COLORWHEEL",
            113,
            0,
            256
        ],
        [
            "FIRE",
            114,
            0,
            256
        ],
        [
            "ISOLUM",
            115,
            0,
            256
        ],
        [
            "KB",
            116,
            0,
            256
        ],
        [
            "KBC",
            117,
            0,
            256
        ],
        [
            "KG",
            118,
            0,
            256
        ],
        [
            "KGY",
            119,
            0,
            256
        ],
        [
            "KR",
            120,
            0,
            256
        ],
        [
            "BLACK_BODY",
            121,
            0,
            256
        ],
        [
            "KINDLMANN",
            122,
            0,
            256
        ],
        [
            "EXTENDED_KINDLMANN",
            123,
            0,
            256
        ],
        [
            "GLASBEY",
            176,
            0,
            256
        ],
        [
            "GLASBEY_COOL",
            177,
            0,
            256
        ],
        [
            "GLASBEY_DARK",
            178,
            0,
            256
        ],
        [
            "GLASBEY_HV",
            179,
            0,
            256
        ],
        [
            "GLASBEY_LIGHT",
            180,
            0,
            256
        ],
        [
            "GLASBEY_WARM",
            181,
            0,
            256
        ],
        [
            "ACCENT",
            240,
            0,
            8
        ],
        [
            "DARK2",
            240,
            32,
            8
        ],
        [
            "PAIRED",
            240,
            64,
            12
        ],
        [
            "PASTEL1",
            240,
            96,
            9
        ],
        [
            "PASTEL2",
            240,
            128,
            8
        ],
        [
            "SET1",
            240,
            160,
            9
        ],
        [
            "SET2",
            240,
            192,
            8
        ],
        [
            "SET3",
            240,
            224,
            12
        ],
        [
            "TAB10",
            241,
            0,
            10
        ],
        [
            "TAB20",
            241,
            32,
            20
        ],
        [
            "TAB20B",
            241,
            64,
            20
        ],
        [
            "TAB20C",
            241,
            96,
            20
        ],
        [
            "CATEGORY10_10",
            241,
            128,
            10
        ],
        [
            "CATEGORY20_20",
            241,
            160,
            20
        ],
        [
            "CATEGORY20B_20",
            241,
            192,
            20
        ],
        [
            "CATEGORY20C_20",
            241,
            224,
            20
        ],
        [
            "COLORBLIND8",
            242,
            0,
            8
        ]
    ]
}